In [58]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder , StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

## 1. Load the dataset

`pd.read_csv()` loads the CSV file into a pandas DataFrame.

In [3]:
df = pd.read_csv("./tested.csv")
print(df)

     PassengerId  Survived  Pclass  \
0            892         0       3
1            893         1       3
2            894         0       2
3            895         0       3
4            896         1       3
..           ...       ...     ...
413         1305         0       3
414         1306         1       1
415         1307         0       3
416         1308         0       3
417         1309         0       3

                                             Name     Sex   Age  SibSp  Parch  \
0                                Kelly, Mr. James    male  34.5      0      0
1                Wilkes, Mrs. James (Ellen Needs)  female  47.0      1      0
2                       Myles, Mr. Thomas Francis    male  62.0      0      0
3                                Wirz, Mr. Albert    male  27.0      0      0
4    Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female  22.0      1      1
..                                            ...     ...   ...    ...    ...
413                            Spector, Mr. Woolf    male   NaN      0      0
414                  Oliva y Ocana, Dona. Fermina  female  39.0      0      0
415                  Saether, Mr. Simon Sivertsen    male  38.5      0      0
416                           Ware, Mr. Frederick    male   NaN      0      0
417                      Peter, Master. Michael J    male   NaN      1      1

                 Ticket      Fare Cabin Embarked
0                330911    7.8292   NaN        Q
1                363272    7.0000   NaN        S
2                240276    9.6875   NaN        Q
3                315154    8.6625   NaN        S
4               3101298   12.2875   NaN        S
..                  ...       ...   ...      ...
413           A.5. 3236    8.0500   NaN        S
414            PC 17758  108.9000  C105        C
415  SOTON/O.Q. 3101262    7.2500   NaN        S
416              359309    8.0500   NaN        S
417                2668   22.3583   NaN        C

[418 rows x 12 columns]

## 2. Basic inspection

`shape` gives rows/columns; `head()` shows the first rows; `info()` shows data types and non-null counts; `isnull().sum()` counts missing values; `dtypes` shows column types.

In [4]:
df.shape

(418, 12)

In [5]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  418 non-null    int64
 1   Survived     418 non-null    int64
 2   Pclass       418 non-null    int64
 3   Name         418 non-null    str
 4   Sex          418 non-null    str
 5   Age          332 non-null    float64
 6   SibSp        418 non-null    int64
 7   Parch        418 non-null    int64
 8   Ticket       418 non-null    str
 9   Fare         417 non-null    float64
 10  Cabin        91 non-null     str
 11  Embarked     418 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 39.3 KB

In [7]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [8]:
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name               str
Sex                str
Age            float64
SibSp            int64
Parch            int64
Ticket             str
Fare           float64
Cabin              str
Embarked           str
dtype: object

## 3. Target distribution

`Survived` is the target. `value_counts()` shows how many rows belong to each class.

In [9]:
df["Survived"].value_counts()

Survived
0    266
1    152
Name: count, dtype: int64

## 4. Separate features and target

`X` contains inputs. `y` contains the target/answer. The target must not be included in `X`.

In [10]:
X = df.drop("Survived", axis=1)
y = df["Survived"]

X.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [11]:
y.head()

0    0
1    1
2    0
3    0
4    1
Name: Survived, dtype: int64

## 5. Remove unused columns

We remove `PassengerId`, `Name`, `Ticket`, and `Cabin` for this learning pipeline. The target `Survived` is also excluded from `X`.

In [12]:
X = df.drop(["Survived", "PassengerId", "Cabin", "Ticket", "Name"], axis=1)
y = df["Survived"]
X.head()

   Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0       3    male  34.5      0      0   7.8292        Q
1       3  female  47.0      1      0   7.0000        S
2       2    male  62.0      0      0   9.6875        Q
3       3    male  27.0      0      0   8.6625        S
4       3  female  22.0      1      1  12.2875        S

## 6. Train/test split

Split **before fitting preprocessing** to prevent data leakage. `test_size=0.2` uses 20% for testing; `random_state=42` makes the split reproducible; `stratify=y` preserves class proportions.

In [13]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(334, 7)
(84, 7)
(334,)
(84,)

In [14]:
print(X_train.columns)

Index(['Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare', 'Embarked'], dtype='str')

## 7. Identify numerical and categorical features

Numerical columns will receive numerical imputation and scaling. Categorical columns will receive categorical imputation and one-hot encoding.

In [15]:
numerical_feacture = ["SibSp", "Pclass", "Age", "Parch", "Fare"]
categorical_feacture = ["Sex", "Embarked"]

print("Numerical Feactures", numerical_feacture)
print("Categorical Feactures", categorical_feacture)

Numerical Feactures ['SibSp', 'Pclass', 'Age', 'Parch', 'Fare']
Categorical Feactures ['Sex', 'Embarked']

## 8. Check missing values

In [16]:
X.isnull().sum()

Pclass       0
Sex          0
Age         86
SibSp        0
Parch        0
Fare         1
Embarked     0
dtype: int64

## 9. Numerical imputation

`SimpleImputer(strategy="median")` learns the median from the training data and uses it to replace missing numerical values. Fitting only on `X_train` prevents test-set leakage.

In [17]:
numerical_imputer = SimpleImputer(strategy="median")
numerical_imputer.fit(X_train[numerical_feacture])

SimpleImputer(strategy='median')

In [18]:
# Learned medians are in the same order as numerical_feacture.
numerical_imputer.statistics_

array([ 0.   ,  3.   , 27.   ,  0.   , 13.775])

In [19]:
# transform() actually replaces missing values using the learned medians.
X_train_num = numerical_imputer.transform(X_train[numerical_feacture])

print(X_train_num.shape)
print(X_train_num[:5])

(334, 5)
[[ 0.      3.     27.      0.      7.    ]
 [ 0.      3.     21.      0.      7.7958]
 [ 0.      3.     27.      0.      7.75  ]
 [ 0.      3.      9.      1.      3.1708]
 [ 0.      3.     27.      0.      7.7792]]

## 10. Categorical imputation

For categories, median is not meaningful. `most_frequent` learns the most common category in each column.

In [20]:
categorical_imputer = SimpleImputer(strategy="most_frequent")
categorical_imputer.fit(X_train[categorical_feacture])

print(categorical_imputer.statistics_)

['male' 'S']

## 11. One-Hot Encoding

Categorical strings such as `male/female` and `C/Q/S` need numerical representations. One-hot encoding creates binary columns. `handle_unknown="ignore"` safely handles categories not seen during fitting.

In [21]:
categorical_encoder = OneHotEncoder(handle_unknown="ignore")

In [22]:
categorical_encoder.fit(X_train[categorical_feacture])
print(categorical_encoder.categories_)

[array(['female', 'male'], dtype=object), array(['C', 'Q', 'S'], dtype=object)]

In [24]:
# Transform categories into binary features.
X_train_cat = categorical_encoder.transform(X_train[categorical_feacture])

print(X_train_cat.shape)
print(X_train_cat[:5])

(334, 5)
<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 10 stored elements and shape (5, 5)>
  Coords	Values
  (0, 1)	1.0
  (0, 4)	1.0
  (1, 1)	1.0
  (1, 4)	1.0
  (2, 1)	1.0
  (2, 3)	1.0
  (3, 1)	1.0
  (3, 4)	1.0
  (4, 0)	1.0
  (4, 3)	1.0

print(X)

     Pclass     Sex   Age  SibSp  Parch      Fare Embarked
0         3    male  34.5      0      0    7.8292        Q
1         3  female  47.0      1      0    7.0000        S
2         2    male  62.0      0      0    9.6875        Q
3         3    male  27.0      0      0    8.6625        S
4         3  female  22.0      1      1   12.2875        S
..      ...     ...   ...    ...    ...       ...      ...
413       3    male   NaN      0      0    8.0500        S
414       1  female  39.0      0      0  108.9000        C
415       3    male  38.5      0      0    7.2500        S
416       3    male   NaN      0      0    8.0500        S
417       3    male   NaN      1      1   22.3583        C

[418 rows x 7 columns]

In [33]:
# scale the numerical feactures

numerical_feacture = ["SibSp" , "Pclass" , "Age" , "Parch" , "Fare"]
numerical_scaler = StandardScaler()
X_train_scaled = numerical_scaler.fit_transform(X_train[numerical_feacture])
print("means" , numerical_scaler.mean_)
print("Scale" , numerical_scaler.scale_)
print(X_train_scaled.shape)
print(X_train_scaled[:5])

means [ 0.44011976  2.27245509 30.47358491  0.38023952 36.48801351]
Scale [ 0.91609428  0.8515688  14.31914548  0.92326805 57.86305774]
(334, 5)
[[-0.48043064  0.85435834         nan -0.41184087 -0.50961727]
 [-0.48043064  0.85435834 -0.66160267 -0.41184087 -0.49586411]
 [-0.48043064  0.85435834         nan -0.41184087 -0.49665563]
 [-0.48043064  0.85435834 -1.49964151  0.6712682  -0.57579421]
 [-0.48043064  0.85435834         nan -0.41184087 -0.49615099]]

In [37]:
X_test_scaled = numerical_scaler.transform(X_test[numerical_feacture])
print(X_test_scaled.shape)
print(X_test_scaled[:5])

(84, 5)
[[-0.48043064  0.85435834         nan -0.41184087 -0.49665563]
 [ 0.61116007 -1.49424813 -0.38225639 -0.41184087  0.32756109]
 [-0.48043064  0.85435834 -0.24258325 -0.41184087 -0.49413589]
 [-0.48043064 -0.31994489 -0.73143924 -0.41184087  0.0045277 ]
 [-0.48043064 -1.49424813 -0.38225639 -0.41184087 -0.18125578]]

In [39]:
numerical_pipeline = Pipeline([("imputer" , SimpleImputer(strategy="median")),
                               ("scaler" , StandardScaler())])

In [41]:
numerical_pipeline.fit(X_train[numerical_feacture])

Pipeline(steps=[('imputer', SimpleImputer(strategy='median')),
                ('scaler', StandardScaler())])

In [42]:
X_train_num = numerical_pipeline.transform(X_train[numerical_feacture])

In [44]:
print(X_train_num.shape)
print(X_train_num[:5])

(334, 5)
[[-0.48043064  0.85435834 -0.21477642 -0.41184087 -0.50908747]
 [-0.48043064  0.85435834 -0.68236136 -0.41184087 -0.49531685]
 [-0.48043064  0.85435834 -0.21477642 -0.41184087 -0.49610938]
 [-0.48043064  0.85435834 -1.61753124  0.6712682  -0.57534842]
 [-0.48043064  0.85435834 -0.21477642 -0.41184087 -0.4956041 ]]

In [51]:
categorical_feacture = ["Sex" , "Embarked"]
categorical_pipeline = Pipeline([("imputer" , SimpleImputer(strategy = "most_frequent")),
                                ("encoder" , OneHotEncoder(handle_unknown="ignore"))
                                ])
categorical_pipeline.fit(X_train[categorical_feacture])

Pipeline(steps=[('imputer', SimpleImputer(strategy='most_frequent')),
                ('encoder', OneHotEncoder(handle_unknown='ignore'))])

In [52]:
X_train_cat = categorical_pipeline.transform(X_train[categorical_feacture])

In [54]:
print(X_train_cat.shape)
print(X_train_cat[:5])

(334, 5)
<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 10 stored elements and shape (5, 5)>
  Coords	Values
  (0, 1)	1.0
  (0, 4)	1.0
  (1, 1)	1.0
  (1, 4)	1.0
  (2, 1)	1.0
  (2, 3)	1.0
  (3, 1)	1.0
  (3, 4)	1.0
  (4, 0)	1.0
  (4, 3)	1.0

In [59]:
preprocessor = ColumnTransformer([("numerical" , numerical_pipeline , numerical_feacture),
                                   ("categorical" , categorical_pipeline , categorical_feacture)])

In [60]:
preprocessor.fit(X_train)

ColumnTransformer(transformers=[('numerical',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='median')),
                                                 ('scaler', StandardScaler())]),
                                 ['SibSp', 'Pclass', 'Age', 'Parch', 'Fare']),
                                ('categorical',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='most_frequent')),
                                                 ('encoder',
                                                  OneHotEncoder(handle_unknown='ignore'))]),
                                 ['Sex', 'Embarked'])])

In [61]:
X_train_processed = preprocessor.transform(X_train)

In [62]:
print(X_train_processed.shape)

(334, 10)

In [67]:
print(np.isnan(X_train_processed).sum())

0

In [68]:
X_test_processed = preprocessor.transform(X_test)

ColumnTransformer(transformers=[('numerical',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='median')),
                                                 ('scaler', StandardScaler())]),
                                 ['SibSp', 'Pclass', 'Age', 'Parch', 'Fare']),
                                ('categorical',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='most_frequent')),
                                                 ('encoder',
                                                  OneHotEncoder(handle_unknown='ignore'))]),
                                 ['Sex', 'Embarked'])])

In [74]:
# get the feactures name that we are created 
feacture_name  = preprocessor.get_feature_names_out()
print(feacture_name)

['numerical__SibSp' 'numerical__Pclass' 'numerical__Age'
 'numerical__Parch' 'numerical__Fare' 'categorical__Sex_female'
 'categorical__Sex_male' 'categorical__Embarked_C'
 'categorical__Embarked_Q' 'categorical__Embarked_S']